- hosts: localhost
  gather_facts: false
  vars:
    new_release: ""
    old_release: ""
    release_prefix: "v"
    quay_org: "quay.io/konveyor"
    quay_bundle_repo: "tackle2-operator-bundle"
    quay_index_repo: "tackle2-operator-index"
  tasks:
  - assert:
      that:
        - new_release != ''
        - old_release != ''
      fail_msg: "new_release and old_release must be provided and must follow semver convention (i.e 2.0.0)"

  - name: "Add new bundle to old index image"
    shell: |
           opm index add -c podman -f {{ quay_org}}/{{ quay_index_repo }}:{{ release_prefix }}{{ old_release }} \
           --bundles {{ quay_org }}/{{ quay_bundle_repo }}:{{ release_prefix}}{{ new_release }} \
           --tag {{ quay_org }}/{{ quay_index_repo }}:{{ release_prefix }}{{ new_release }}

  - name: "Push updated index as a new image"
    shell: podman push {{ quay_org }}/{{ quay_index_repo }}:{{ release_prefix }}{{ new_release }}

  - name: "Add development bundle to the new index"
    shell: |
           opm index add -c podman -f {{ quay_org }}/{{ quay_index_repo }}:{{ release_prefix }}{{ new_release }} \
           --bundles {{ quay_org }}/{{ quay_bundle_repo }}:latest \
           --tag {{ quay_org }}/{{ quay_index_repo }}:latest

  - name: "Push the complete index to latest"
    shell: podman push {{ quay_org }}/{{ quay_index_repo }}:latest
